import {Song} from '../shared/types'

export const songs : Song[] = [
{
  album_Name: "Abbey Road",      
  song_title: "Come Together",
  artist: "The Beatles",
  track_length: 4.20,
  genre: "Rock",
  released: 1969,
},
{
  album_Name: "Abbey Road",      
  song_title: "Something",
  artist: "The Beatles",
  track_length: 3.30,
  genre: "Rock",
  released: 1969,
},
{
  album_Name: "Abbey Road",      
  song_title: "Maxwell's Silver Hammer",
  artist: "The Beatles",
  track_length: 3.27,
  genre: "Rock",
  released: 1969,
},
{
  album_Name: "Abbey Road",      
  song_title: "Oh! Darling",
  artist: "The Beatles",
  track_length: 3.27,
  genre: "Rock",
  released: 1969,
},
{
  album_Name: "Abbey Road",      
  song_title: "Octopus's Garden",
  artist: "The Beatles",
  track_length: 2.51,
  genre: "Rock",
  released: 1969,
},
{
  album_Name: "Abbey Road",      
  song_title: "I Want You(She's So Heavy)",
  artist: "The Beatles",
  track_length: 7.47,
  genre: "Rock",
  released: 1969,
},
{
  album_Name: "Abbey Road",      
  song_title: "Here Comes the Sun",
  artist: "The Beatles",
  track_length: 3.60,
  genre: "Rock",
  released: 1969,
},
{
  album_Name: "Abbey Road",      
  song_title: "Because",
  artist: "The Beatles",
  track_length: 2.46,
  genre: "Rock",
  released: 1969,
},
{
  album_Name: "Abbey Road",      
  song_title: "You Never Give Me Your Money",
  artist: "The Beatles",
  track_length: 4.02,
  genre: "Rock",
  released: 1969,
},
{
  album_Name: "Abbey Road",      
  song_title: "Sun King",
  artist: "The Beatles",
  track_length: 2.26,
  genre: "Rock",
  released: 1969,
},
{
  album_Name: "Abbey Road",      
  song_title: "Mean Mr.Mustard",
  artist: "The Beatles",
  track_length: 1.06,
  genre: "Rock",
  released: 1969,
},
{
  album_Name: "Abbey Road",      
  song_title: "Polythene Pam",
  artist: "The Beatles",
  track_length: 1.13,
  genre: "Rock",
  released: 1969,
},
{
  album_Name: "Abbey Road",      
  song_title: "She Came In Through The Bathroom Window",
  artist: "The Beatles",
  track_length: 1.58,
  genre: "Rock",
  released: 1969,
},
{
  album_Name: "Abbey Road",      
  song_title: "Golden Slumbers",
  artist: "The Beatles",
  track_length: 1.32,
  genre: "Rock",
  released: 1969,
},
{
  album_Name: "Abbey Road",      
  song_title: "Carry That Weight",
  artist: "The Beatles",
  track_length: 1.37,
  genre: "Rock",
  released: 1969,
},
{
  album_Name: "Abbey Road",      
  song_title: "The End",
  artist: "The Beatles",
  track_length: 2.20,
  genre: "Rock",
  released: 1969,
},
{
  album_Name: "Abbey Road",      
  song_title: "Her Majesty",
  artist: "The Beatles",
  track_length: 0.23,
  genre: "Rock",
  released: 1969,
}
]



